### ISSUE TITLE
WooCommerce not updating order status

### ISSUE THREAD

**Issue by lsfiege** [claudiosanches/woocommerce-mercadopago#20]
Hi Claudio! I have installed and properly configurated the woocommerce-mercagopago plugin en my site and have setted the IPN response url.

But it seems the plugin is not updating the status of any order in any case, can you check this?

In the log i see this: 
`12-29-2016 @ 21:31:37 - Received valid IPN response from MercadoPago

12-29-2016 @ 21:31:37 - Payment status from order 2192: approved.

12-29-2016 @ 21:31:38 - IPN Response: Array (...)`

But the order nº 2192 still in "processing" state in "orders" section of woocommerce

greetings

Edit: woocommerce v2.6.11 and woocommerce-mercadopago v2.0.8

**Comment by claudiosanches** [comment]
> But the order nº 2192 still in "processing" state in "orders" section of woocommerce

This means that the order status is updating correctly, since the order status start on "oh-hold" and can go to "cancelled", "refunded" or "processing".

**Comment by lsfiege** [comment]
thanks

**Comment by claudiosanches** [comment]
@lsfiege not to forget that all WooCommerce payment gateways should never change the status to "complete", since "complete" is something manual and requires your attention.
